easy_admin:
    entities:
        - App\Entity\Carga
        - App\Entity\Destinatario
        - App\Entity\Entregador
        - App\Entity\Pacote
        - App\Entity\Rota
        - App\Entity\Pacote\Item
